[project]
name = "comfyui-imageoptionpicker"
description = "A node to pause the workflow to select one of the three generated images for further processing."
version = "1.0.0"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = []

[project.urls]
Repository = "https://github.com/lalikamala/ComfyUI-ImageOptionPicker"

[tool.comfy]
PublisherId = "lalikamala"
DisplayName = "ComfyUI Image Option Picker"
Icon = "https://raw.githubusercontent.com/lalikamala/ComfyUI-ImageOptionPicker/main/icon.png"